apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  name: {{ .Release.Name }}
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: ms-go-auth
            port: 
              number: 6000
      - path: /login
        pathType: Prefix
        backend:
          service:
            name: ms-go-auth
            port: 
              number: 6000
      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: ms-go-crud
            port: 
              number: 7000
      - path: /user
        pathType: Prefix
        backend:
          service:
            name: ms-go-crud
            port: 
              number: 7000
      - path: /users
        pathType: Prefix
        backend:
          service:
            name: ms-go-crud
            port: 
              number: 7000