apiVersion: v1
kind: Pod
metadata:
  labels:
    component: ci
spec:
  # Use service account that can deploy to all namespaces
  serviceAccountName: jenkins
  containers:
  - name: gcloud
    image: gcr.io/cloud-builders/gcloud
    command: ['cat']
    tty: true
  - name: helm
    image: alpine/helm:2.14.0
    imagePullPolicy: IfNotPresent
    command:
    - cat
    tty: true