def appName = "ms-go-crud"
def namespace = "coding-test"

pipeline {
  agent {
    kubernetes {
      // Without cloud, Jenkins will pick the first cloud in the list
      cloud "kubernetes"
      label "jenkins-agent"
    }
  }

  stages {
    stage("Build") {
      steps {
        dir("ms-go-crud") {
          container("gcloud") {
            // Cheat by using Cloud Build to help us build our container
            sh "gcloud builds submit -t ${params.IMAGE_URL}:${GIT_COMMIT}"
          }
        }
      }
    }
    stage("Deploy to Kubernetes") {
        steps {
        container("helm") {
          sh """
              helm upgrade ${appName} ./helm/${appName} \
                --set-string image.repository=${params.IMAGE_URL},image.tag=${GIT_COMMIT} \
                --debug --install --namespace ${namespace}
            """
        }
      }
    }
  }
}