apiVersion: v1
kind: Pod
metadata:
  labels:
    component: ci
spec:
  # Use service account that can deploy to all namespaces
  serviceAccountName: jenkins
  containers:
  # - name: gcloud
  #   image: google/cloud-sdk:272.0.0-alpine
  #   command:
  #   - cat
  #   tty: true
  - name: gcloud
    image: gcr.io/cloud-builders/gcloud
    command: ['cat']
    tty: true
  - name: helm
    image: alpine/helm:2.14.0
    imagePullPolicy: IfNotPresent
    command:
    - cat
    tty: true
    volumeMounts: # Path dari directory yang akan digunakan dan di mount ke PV
      - name: jenkins-agent-data
        mountPath:  '/data'

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-agent-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi