apiVersion: v1
kind: Pod
metadata:
  labels:
    component: ci
spec:
  # Use service account that can deploy to all namespaces
  serviceAccountName: cd-jenkins
  containers:
  # - name: gcloud
  #   image: google/cloud-sdk:272.0.0-alpine
  #   command:
  #   - cat
  #   tty: true
  - name: gcloud
    image: gcr.io/cloud-builders/gcloud
    command: ['cat']
    tty: true
  - name: helm
    image: alpine/helm:latest
    imagePullPolicy: IfNotPresent
    command:
    - cat
    tty: true